name: Continuous Delivery
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'
  workflow_dispatch:

jobs:
  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Use Node.js v18
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "18.x"
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Build Code
        run: yarn compile
      - name: TypeCheck
        run: yarn typecheck

  Deploying:
    name: Deploying NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: akhileshns/heroku-deploy@5ef17ff17a3fb8e9ad822ae6a61648a3ef9e0c3d # v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radon-dev"
          heroku_email: ${{secrets.EMAIL}}

  Backup:
    name: Backup NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: akhileshns/heroku-deploy@5ef17ff17a3fb8e9ad822ae6a61648a3ef9e0c3d # v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY2}}
          heroku_app_name: "radon-dev2"
          heroku_email: ${{secrets.EMAIL2}}
