name: Continuous Delivery
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'src/**'
  #     - '.github/workflows/continuous-delivery.yml'
  #     - 'package.json'
  workflow_dispatch:

jobs:
  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js v18
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: "18.x"
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Build Code
        run: yarn compile
      - name: TypeCheck
        run: yarn typecheck

  Deploying:
    name: Deploying NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0 # v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radon-dev"
          heroku_email: ${{secrets.EMAIL}}

  Backup:
    name: Backup NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0 # v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY2}}
          heroku_app_name: "radon-dev2"
          heroku_email: ${{secrets.EMAIL2}}
