name: Continuous Delivery
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/continuous-delivery.yml'
      - 'package.json'
  workflow_dispatch:

jobs:
  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Use Node.js v18
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: "18.x"
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Build Code
        run: yarn compile
      - name: TypeCheck
        run: yarn typecheck

  Deploying:
    name: Deploying NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820 # tag=v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radon-dev"
          heroku_email: ${{secrets.EMAIL}}

  Backup:
    name: Backup NodeJS
    runs-on: ubuntu-latest
    needs: [Building]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820 # tag=v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY2}}
          heroku_app_name: "radon-dev2"
          heroku_email: ${{secrets.EMAIL2}}
